FROM debian:latest

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    && apt-get clean

WORKDIR /app

COPY . .

RUN mkdir -p build && cd build \
    && cmake .. \
    && cmake --build .

CMD ["./scripts/docker_test.bash"]